### ISSUE TITLE
Project 2, Section 2, Graph 4

### ISSUE THREAD

**Issue by scottmarshall17** [mackncheesiest/ECE478_Projects#10]
Must create a graph that is similar to graph 1, but breaks up the data by type of AS. My plan is to scrub the data using C++, for its speed, and then use the resulting file to create a graph using MATLAB.

**Comment by scottmarshall17** [comment]
All of the data for graph 4 is located in the '2.2 Data' folder. We just need to create the pie chart now. There are 55583 ASs total in the file. The data is laid out like this:

<Enterprise ASs>
<Content ASs>
<Transit ASs>

**Comment by mackncheesiest** [comment]
So, the left is Graph 1, and the right is Graph 4
![image](https://cloud.githubusercontent.com/assets/8922497/20083746/5f446a80-a51b-11e6-93dd-4fd9bea14b02.png)

**Comment by scottmarshall17** [comment]
Do you feel like the results are correct? I've included the C++ code in the scripts folder if you want to check the classification logic. It makes sense that enterprise ASes hold the majority, since those represent consumers. I'm kind of surprised by the change in % of transit ASes. What are your thoughts?

**Comment by mackncheesiest** [comment]
So I've been wondering, what is this "dataFile.txt" that is used as the input filename in this file? Is it just the 20161001.as-rel2 file? That's what seems like it would be to me, but just want to make sure.

**Comment by mackncheesiest** [comment]
Oh man, looking at Piazza, this is [certainly interesting](https://piazza.com/class/is6dw3c76i74y?cid=171)

Yeah, those classification rules are going to change things.

**Comment by mackncheesiest** [comment]
Anyway, other than that, this code looks fine, too. So I'll get the 2.3 table done tonight and then I think we'll be in good shape for just polishing things up tomorrow.

**Comment by scottmarshall17** [comment]
Yep, the dataFile.txt is just the 20161001.as-rel2 file. I was just lazy and thought it would be easy to just rename the file for convenience. 

As to the new classification rules Lazos posted on the fly? Yep, I ran into the issue yesterday where some ASes weren't falling under any category and stumbled upon that post. Crazy, right?

**Comment by mackncheesiest** [comment]
![image](https://cloud.githubusercontent.com/assets/8922497/20129634/5b3aa01e-a60e-11e6-8d1c-cd2e352919ca.png)

**Comment by mackncheesiest** [comment]
Closed in some kind of commit
