### ISSUE TITLE
Project 2, Section 2.2, Graph 2

### ISSUE THREAD

**Issue by mackncheesiest** [mackncheesiest/ECE478_Projects#8]
Need to complete section 2.2 as listed in the project's PDF

**Comment by scottmarshall17** [comment]
I'm going to start working on graph 2 with the histogram. I'll let you know when it's finished

**Comment by mackncheesiest** [comment]
Closed in c796f6105bfd905653e8600747784851d9cf4c77

**Comment by mackncheesiest** [comment]
Figured I'd let you know I read through the Matlab implementation to make sure I understood the different assumptions/things that we're using, and it all looks good to me.
