### ISSUE TITLE
Project 2, Section 2.2, Graph 3

### ISSUE THREAD

**Issue by scottmarshall17** [mackncheesiest/ECE478_Projects#9]
This is the next logical step after Graph 2

**Comment by scottmarshall17** [comment]
I believe that Dr. Lazos wants a histogram broken up into bins regarding the number of IP addresses available to each AS. My first plan of attack is to count the number of IP addresses associated with each AS and then play around with the bin size afterward. I think I'll also try to implement this in C++ first because the application runs in under 2 seconds as opposed to 7 minutes with MATLAB

**Comment by scottmarshall17** [comment]
I wrote a C++ application to sift through the data and calculate the number of IP addresses associates with each AS. That data is now in the file 'ipSpaceDataG3.txt' in the 2.2 Data folder. Each line is the number of IP addresses owned by a unique AS, since this data only needs to turn into a histogram I left the AS identification number out of the file for easy processing. All that needs to be done now is create a normalized histogram of the IP address space owned by each AS based on our choice of bin constraints.

**Comment by mackncheesiest** [comment]
Oh sweet! This project is definitely a lot smoother than the last one. 

Do you want me to do 2.2 part 4 or move right on to 2.3?

**Comment by scottmarshall17** [comment]
Just create a new issue for whichever option you choose. Preferably the table for 2.3 if you want my suggestion. Also, what kind of bins should we use for the AS IP address space data? And what does he mean when he says he wants the data normalized?

**Comment by mackncheesiest** [comment]
Pretty sure he's talking about something along the lines of Piazza [186](https://piazza.com/class/is6dw3c76i74y?cid=186)

**Comment by scottmarshall17** [comment]
Awesome! The largest AS owns only 2.812% of the overall IP space. How many bins do you think we should use in our graph? That should dictate what bins we use.

**Comment by mackncheesiest** [comment]
I would definitely say not so many that you can't tell there even are bins anymore 😛 

Turns out colon opens an emoji menu <:stuck_out_tongue>

**Comment by scottmarshall17** [comment]
😜  <:stuck_out_tongue_winking_eye> lol

**Comment by mackncheesiest** [comment]
So...are we supposed to just use the classification bins that we used to group the data in the first place?
i.e. some kind of histogram along the lines of 

"nodes with degrees of 1 take up X1 percentage of the IP space, nodes with degrees 2-5 take up X2 percentage of the IP space, ..."?

**Comment by mackncheesiest** [comment]
Or maybe that's too similar to graph 2

**Comment by scottmarshall17** [comment]
We could break the bins up into the percentage of IP address space they own in increments of 0.1% up to the 2.81...% held by the largest AS. Does that sound like a viable bin strategy?

**Comment by mackncheesiest** [comment]
Yeah I think that sounds fine

**Comment by mackncheesiest** [comment]
Do we need to do anything to take into account that sometimes the ASes are [comma separated](https://piazza.com/class/is6dw3c76i74y?cid=184)?

Correct me if I'm wrong, but it looks like we currently only take into account [underscore separation](https://github.com/mackncheesiest/ECE478_Projects/blob/cc8e2710d4d6f612b04c8e4fc34ecd8dff21e5aa/Project2/Scripts/Graph3.cpp#L30)

**Comment by scottmarshall17** [comment]
Hmm, I guess I didn't see any comma separated ASes when I wrote up my script. I can make the change if comma separated ASes exist in the data.

**Comment by scottmarshall17** [comment]
The data file is not updated with the change. Good catch!

**Comment by mackncheesiest** [comment]
Cool, and the rest of this file looks good to me, too

**Comment by mackncheesiest** [comment]
Fun fact: Looks like that 2.81% of the IPv4 space being used by a single AS is from AS 4134 which maps to a thing owned by China Telecom, a big Chinese ISP

**Comment by mackncheesiest** [comment]
Closed...somewhere
